///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpdatePatient
{
    /// <summary>
    ///The adminIan recording.
    /// </summary>
    [TestModule("e33078ec-6a50-46c0-9b7d-31b70989304e", ModuleType.Recording, 1)]
    public partial class AdminIan : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpdatePatientRepository repository.
        /// </summary>
        public static UpdatePatientRepository repo = UpdatePatientRepository.Instance;

        static AdminIan instance = new AdminIan();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AdminIan()
        {
            Browsers = "Chrome";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AdminIan Instance
        {
            get { return instance; }
        }

#region Variables

        string _Browsers;

        /// <summary>
        /// Gets or sets the value of variable Browsers.
        /// </summary>
        [TestVariable("9ab0cf5b-af0e-40bb-b985-4f0e2e64edd1")]
        public string Browsers
        {
            get { return _Browsers; }
            set { _Browsers = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://neutron.plexia.local/emrwebtest3_modal/\r\n' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://neutron.plexia.local/emrwebtest3_modal/\r\n", "IE", "", false, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.PlexiaMainFrame.LoginPage.TxtUserName' at 42;10.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.LoginPage.TxtUserNameInfo, new RecordItemIndex(1));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.LoginPage.TxtUserName.Click("42;10");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin_{LShiftKey up}ian{Tab}' with focus on 'PLEXIAEMRTest3Modal.PlexiaMainFrame.LoginPage.TxtUserName'.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.LoginPage.TxtUserNameInfo, new RecordItemIndex(2));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.LoginPage.TxtUserName.PressKeys("admin_{LShiftKey up}ian{Tab}");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'plexiadev'.", new RecordItemIndex(3));
            Keyboard.Press("plexiadev");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.PlexiaMainFrame.LoginPage.BtnLogin' at 21;8.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.LoginPage.BtnLoginInfo, new RecordItemIndex(4));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.LoginPage.BtnLogin.Click("21;8");
            
        }

#region Image Feature Data
#endregion
    }
}
