///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpdatePatient
{
    /// <summary>
    ///The ChangeAge recording.
    /// </summary>
    [TestModule("2686235b-f670-4199-9582-5488229ea662", ModuleType.Recording, 1)]
    public partial class ChangeAge : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpdatePatientRepository repository.
        /// </summary>
        public static UpdatePatientRepository repo = UpdatePatientRepository.Instance;

        static ChangeAge instance = new ChangeAge();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChangeAge()
        {
            AgeVariable = "12/12/2013";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChangeAge Instance
        {
            get { return instance; }
        }

#region Variables

        string _AgeVariable;

        /// <summary>
        /// Gets or sets the value of variable AgeVariable.
        /// </summary>
        [TestVariable("daedfd65-b02d-4c51-a2a2-4ab20cde0951")]
        public string AgeVariable
        {
            get { return _AgeVariable; }
            set { _AgeVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.PlexiaMainFrame.PatientRecords.LinkPersonal' at 50;4.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.PatientRecords.LinkPersonalInfo, new RecordItemIndex(0));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.PatientRecords.LinkPersonal.Click("50;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Middle DoubleClick item 'PLEXIAEMRTest3Modal.PlexiaMainFrame.TxtDOB' at 82;14.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.TxtDOBInfo, new RecordItemIndex(1));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.TxtDOB.DoubleClick(System.Windows.Forms.MouseButtons.Middle, "82;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}' with focus on 'PLEXIAEMRTest3Modal.PlexiaMainFrame.TxtDOB'.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.TxtDOBInfo, new RecordItemIndex(2));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.TxtDOB.PressKeys("{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $AgeVariable with focus on 'PLEXIAEMRTest3Modal.PlexiaMainFrame.TxtDOB'.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.TxtDOBInfo, new RecordItemIndex(3));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.TxtDOB.PressKeys(AgeVariable);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.PlexiaMainFrame.PersonalProfile.BtnUpdatePatient' at 75;9.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.PersonalProfile.BtnUpdatePatientInfo, new RecordItemIndex(4));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.PersonalProfile.BtnUpdatePatient.Click("75;9");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
}
