///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpdatePatient
{
    /// <summary>
    ///The CloseOutstanding recording.
    /// </summary>
    [TestModule("cbb516d6-8849-47ca-b7f0-b5ed6331323f", ModuleType.Recording, 1)]
    public partial class CloseOutstanding : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpdatePatientRepository repository.
        /// </summary>
        public static UpdatePatientRepository repo = UpdatePatientRepository.Instance;

        static CloseOutstanding instance = new CloseOutstanding();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseOutstanding()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseOutstanding Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OutstandingPopUpModal.Close' at 19;7.", repo.OutstandingPopUpModal.CloseInfo, new RecordItemIndex(0));
            repo.OutstandingPopUpModal.Close.Click("19;7");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
}
