///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpdatePatient
{
    /// <summary>
    ///The CreateEncounter recording.
    /// </summary>
    [TestModule("5896b8a8-fc6d-434f-a29a-58f2aec966dc", ModuleType.Recording, 1)]
    public partial class CreateEncounter : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpdatePatientRepository repository.
        /// </summary>
        public static UpdatePatientRepository repo = UpdatePatientRepository.Instance;

        static CreateEncounter instance = new CreateEncounter();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateEncounter()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateEncounter Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.PlexiaMainFrame.ImgEncounters' at 102;16.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.ImgEncountersInfo, new RecordItemIndex(0));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.ImgEncounters.Click("102;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.PlexiaMainFrame.LinkEncounter' at 12;6.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.LinkEncounterInfo, new RecordItemIndex(1));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.LinkEncounter.Click("12;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.PlexiaMainFrame.View' at 13;7.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.ViewInfo, new RecordItemIndex(2));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.View.Click("13;7");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
}
