///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpdatePatient
{
    /// <summary>
    ///The EncounterFeeCodeCheck recording.
    /// </summary>
    [TestModule("b9efef57-d501-49aa-9a60-1265b82fe1f9", ModuleType.Recording, 1)]
    public partial class EncounterFeeCodeCheck : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpdatePatientRepository repository.
        /// </summary>
        public static UpdatePatientRepository repo = UpdatePatientRepository.Instance;

        static EncounterFeeCodeCheck instance = new EncounterFeeCodeCheck();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EncounterFeeCodeCheck()
        {
            Feecode = "18100";
            Feecode2 = "18100";
            Feecode3 = "18100";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EncounterFeeCodeCheck Instance
        {
            get { return instance; }
        }

#region Variables

        string _Feecode;

        /// <summary>
        /// Gets or sets the value of variable Feecode.
        /// </summary>
        [TestVariable("c2476d29-bf3a-44a0-a5e3-300fe9af2b1e")]
        public string Feecode
        {
            get { return _Feecode; }
            set { _Feecode = value; }
        }

        string _Feecode2;

        /// <summary>
        /// Gets or sets the value of variable Feecode2.
        /// </summary>
        [TestVariable("0d8aa7c8-51a8-4d96-84bd-0a7d639aeae9")]
        public string Feecode2
        {
            get { return _Feecode2; }
            set { _Feecode2 = value; }
        }

        string _Feecode3;

        /// <summary>
        /// Gets or sets the value of variable Feecode3.
        /// </summary>
        [TestVariable("e3fbc580-8ce0-4329-8654-7b6f9663598c")]
        public string Feecode3
        {
            get { return _Feecode3; }
            set { _Feecode3 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee1' at 26;8.", repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee1Info, new RecordItemIndex(0));
            repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee1.DoubleClick("26;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}100' with focus on 'PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee1'.", repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee1Info, new RecordItemIndex(1));
            repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee1.PressKeys("{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.PatientHeaderPopup1Ctl02' at Center.", repo.PLEXIAEMRTest3Modal.SearchBar.PatientHeaderPopup1Ctl02Info, new RecordItemIndex(2));
            repo.PLEXIAEMRTest3Modal.SearchBar.PatientHeaderPopup1Ctl02.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value=$Feecode) on item 'PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee1'.", repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee1Info, new RecordItemIndex(3));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee1Info, "Value", Feecode);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee2' at 22;9.", repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee2Info, new RecordItemIndex(4));
            repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee2.DoubleClick("22;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}101' with focus on 'PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee2'.", repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee2Info, new RecordItemIndex(5));
            repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee2.PressKeys("{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}101");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.PatientHeaderPopup1Ctl02' at Center.", repo.PLEXIAEMRTest3Modal.SearchBar.PatientHeaderPopup1Ctl02Info, new RecordItemIndex(6));
            repo.PLEXIAEMRTest3Modal.SearchBar.PatientHeaderPopup1Ctl02.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value=$Feecode2) on item 'PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee2'.", repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee2Info, new RecordItemIndex(7));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee2Info, "Value", Feecode2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee3' at 30;10.", repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee3Info, new RecordItemIndex(8));
            repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee3.DoubleClick("30;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}110' with focus on 'PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee3'.", repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee3Info, new RecordItemIndex(9));
            repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee3.PressKeys("{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}110");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.PatientHeaderPopup1Ctl02' at Center.", repo.PLEXIAEMRTest3Modal.SearchBar.PatientHeaderPopup1Ctl02Info, new RecordItemIndex(10));
            repo.PLEXIAEMRTest3Modal.SearchBar.PatientHeaderPopup1Ctl02.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value=$Feecode3) on item 'PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee3'.", repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee3Info, new RecordItemIndex(11));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Billing1TxtFee3Info, "Value", Feecode3);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.BtnCancel1' at 33;12.", repo.PLEXIAEMRTest3Modal.SearchBar.BtnCancel1Info, new RecordItemIndex(12));
            repo.PLEXIAEMRTest3Modal.SearchBar.BtnCancel1.Click("33;12");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
}
