///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpdatePatient
{
    /// <summary>
    ///The NotesAlign recording.
    /// </summary>
    [TestModule("25d4ab55-0b59-4d48-b3e6-1590ce6c0f2d", ModuleType.Recording, 1)]
    public partial class NotesAlign : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpdatePatientRepository repository.
        /// </summary>
        public static UpdatePatientRepository repo = UpdatePatientRepository.Instance;

        static NotesAlign instance = new NotesAlign();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NotesAlign()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NotesAlign Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.PlexiaMainFrame.PatientRecords.ImgNotes' at 40;21.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.PatientRecords.ImgNotesInfo, new RecordItemIndex(0));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.PatientRecords.ImgNotes.Click("40;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.PlexiaMainFrame.BtnNewRichTextNote' at Center.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.BtnNewRichTextNoteInfo, new RecordItemIndex(1));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.BtnNewRichTextNote.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.JustifyLeft' at 4;8.", repo.PLEXIAEMRTest3Modal.SearchBar.JustifyLeftInfo, new RecordItemIndex(2));
            repo.PLEXIAEMRTest3Modal.SearchBar.JustifyLeft.Click("4;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'line1'.", new RecordItemIndex(3));
            Keyboard.Press("line1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}line2'.", new RecordItemIndex(4));
            Keyboard.Press("{Return}line2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.JustifyCenter' at 10;10.", repo.PLEXIAEMRTest3Modal.SearchBar.JustifyCenterInfo, new RecordItemIndex(5));
            repo.PLEXIAEMRTest3Modal.SearchBar.JustifyCenter.Click("10;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}line3'.", new RecordItemIndex(6));
            Keyboard.Press("{Return}line3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.JustifyRight' at 12;15.", repo.PLEXIAEMRTest3Modal.SearchBar.JustifyRightInfo, new RecordItemIndex(7));
            repo.PLEXIAEMRTest3Modal.SearchBar.JustifyRight.Click("12;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}line4'.", new RecordItemIndex(8));
            Keyboard.Press("{Return}line4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.JustifyCenter' at 9;8.", repo.PLEXIAEMRTest3Modal.SearchBar.JustifyCenterInfo, new RecordItemIndex(9));
            repo.PLEXIAEMRTest3Modal.SearchBar.JustifyCenter.Click("9;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}line5'.", new RecordItemIndex(10));
            Keyboard.Press("{Return}line5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.JustifyLeft' at 4;8.", repo.PLEXIAEMRTest3Modal.SearchBar.JustifyLeftInfo, new RecordItemIndex(11));
            repo.PLEXIAEMRTest3Modal.SearchBar.JustifyLeft.Click("4;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.HTML' at 27;10.", repo.PLEXIAEMRTest3Modal.SearchBar.HTMLInfo, new RecordItemIndex(12));
            repo.PLEXIAEMRTest3Modal.SearchBar.HTML.Click("27;10");
            Delay.Milliseconds(200);
            
            Validate_RichtextboxHTML();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.Design' at 23;12.", repo.PLEXIAEMRTest3Modal.SearchBar.DesignInfo, new RecordItemIndex(14));
            repo.PLEXIAEMRTest3Modal.SearchBar.Design.Click("23;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='line1') on item 'PLEXIAEMRTest3Modal.SearchBar.Line1'.", repo.PLEXIAEMRTest3Modal.SearchBar.Line1Info, new RecordItemIndex(15));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Line1Info, "InnerText", "line1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='line2') on item 'PLEXIAEMRTest3Modal.SearchBar.Line2'.", repo.PLEXIAEMRTest3Modal.SearchBar.Line2Info, new RecordItemIndex(16));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Line2Info, "InnerText", "line2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Align='center') on item 'PLEXIAEMRTest3Modal.SearchBar.Line2'.", repo.PLEXIAEMRTest3Modal.SearchBar.Line2Info, new RecordItemIndex(17));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Line2Info, "Align", "center");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='line3') on item 'PLEXIAEMRTest3Modal.SearchBar.Line3'.", repo.PLEXIAEMRTest3Modal.SearchBar.Line3Info, new RecordItemIndex(18));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Line3Info, "InnerText", "line3");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Align='right') on item 'PLEXIAEMRTest3Modal.SearchBar.Line3'.", repo.PLEXIAEMRTest3Modal.SearchBar.Line3Info, new RecordItemIndex(19));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Line3Info, "Align", "right");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='line4') on item 'PLEXIAEMRTest3Modal.SearchBar.Line4'.", repo.PLEXIAEMRTest3Modal.SearchBar.Line4Info, new RecordItemIndex(20));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Line4Info, "InnerText", "line4");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Align='center') on item 'PLEXIAEMRTest3Modal.SearchBar.Line4'.", repo.PLEXIAEMRTest3Modal.SearchBar.Line4Info, new RecordItemIndex(21));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Line4Info, "Align", "center");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='line5') on item 'PLEXIAEMRTest3Modal.SearchBar.Line5'.", repo.PLEXIAEMRTest3Modal.SearchBar.Line5Info, new RecordItemIndex(22));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Line5Info, "InnerText", "line5");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Align='left') on item 'PLEXIAEMRTest3Modal.SearchBar.Line5'.", repo.PLEXIAEMRTest3Modal.SearchBar.Line5Info, new RecordItemIndex(23));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.Line5Info, "Align", "left");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
}
