///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace UpdatePatient
{
    public partial class NotesAlign
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Validate_RichtextboxHTML()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='<p>line1</p>\n<p style=\";\" align=\"center\">line2</p>\n<p style=\";\" align=\"right\">line3</p>\n<p style=\";\" align=\"center\">line4</p>\n<p style=\";\" align=\"left\">line5</p>') on item 'PLEXIAEMRTest3Modal.SearchBar.RichtextboxHTML'.", repo.PLEXIAEMRTest3Modal.SearchBar.RichtextboxHTMLInfo);            
            try {
            	Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.RichtextboxHTMLInfo, "TagValue", "<p>line1</p>\n<p style=\";\" align=\"center\">line2</p>\n<p style=\";\" align=\"right\">line3</p>\n<p style=\";\" align=\"center\">line4</p>\n<p style=\";\" align=\"left\">line5</p>");
            } catch(ValidationException){
            	Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.RichtextboxHTMLInfo, "TagValue", "<P>line1</P>\n<P style=\";\" align=\"center\">line2</P>\n<P style=\";\" align=\"right\">line3</P>\n<P style=\";\" align=\"center\">line4</P>\n<P style=\";\" align=\"left\">line5</P>");
            }
        }

    }
}
