///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UpdatePatient
{
    /// <summary>
    /// The class representing the UpdatePatientRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
    [RepositoryFolder("87c65d34-3edb-4e7e-b5f7-ae9175948e72")]
    public partial class UpdatePatientRepository : RepoGenBaseFolder
    {
        static UpdatePatientRepository instance = new UpdatePatientRepository();
        UpdatePatientRepositoryFolders.PLEXIAEMRTest3ModalAppFolder _plexiaemrtest3modal;
        UpdatePatientRepositoryFolders.OutstandingPopUpModalAppFolder _outstandingpopupmodal;
        UpdatePatientRepositoryFolders.HttpsNeutronPlexiaLocalUtilitieAppFolder _httpsneutronplexialocalutilitie;

        /// <summary>
        /// Gets the singleton class instance representing the UpdatePatientRepository element repository.
        /// </summary>
        [RepositoryFolder("87c65d34-3edb-4e7e-b5f7-ae9175948e72")]
        public static UpdatePatientRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public UpdatePatientRepository() 
            : base("UpdatePatientRepository", "/", null, 0, false, "87c65d34-3edb-4e7e-b5f7-ae9175948e72", ".\\RepositoryImages\\UpdatePatientRepository87c65d34.rximgres")
        {
            _plexiaemrtest3modal = new UpdatePatientRepositoryFolders.PLEXIAEMRTest3ModalAppFolder(this);
            _outstandingpopupmodal = new UpdatePatientRepositoryFolders.OutstandingPopUpModalAppFolder(this);
            _httpsneutronplexialocalutilitie = new UpdatePatientRepositoryFolders.HttpsNeutronPlexiaLocalUtilitieAppFolder(this);
        }

#region Variables

        string _RichTextPage = "";

        /// <summary>
        /// Gets or sets the value of variable RichTextPage.
        /// </summary>
        [TestVariable("6ded1961-adac-486c-b286-4540ccac922f")]
        public string RichTextPage
        {
            get { return _RichTextPage; }
            set { _RichTextPage = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("87c65d34-3edb-4e7e-b5f7-ae9175948e72")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The PLEXIAEMRTest3Modal folder.
        /// </summary>
        [RepositoryFolder("785ea004-1522-4869-986f-3f27b57b7427")]
        public virtual UpdatePatientRepositoryFolders.PLEXIAEMRTest3ModalAppFolder PLEXIAEMRTest3Modal
        {
            get { return _plexiaemrtest3modal; }
        }

        /// <summary>
        /// The OutstandingPopUpModal folder.
        /// </summary>
        [RepositoryFolder("0264dd79-1ad5-4ee9-b70a-c2741ed90c3d")]
        public virtual UpdatePatientRepositoryFolders.OutstandingPopUpModalAppFolder OutstandingPopUpModal
        {
            get { return _outstandingpopupmodal; }
        }

        /// <summary>
        /// The HttpsNeutronPlexiaLocalUtilitie folder.
        /// </summary>
        [RepositoryFolder("16ca41fb-0a34-4088-b717-b5fd2811a53a")]
        public virtual UpdatePatientRepositoryFolders.HttpsNeutronPlexiaLocalUtilitieAppFolder HttpsNeutronPlexiaLocalUtilitie
        {
            get { return _httpsneutronplexialocalutilitie; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
    public partial class UpdatePatientRepositoryFolders
    {
        /// <summary>
        /// The PLEXIAEMRTest3ModalAppFolder folder.
        /// </summary>
        [RepositoryFolder("785ea004-1522-4869-986f-3f27b57b7427")]
        public partial class PLEXIAEMRTest3ModalAppFolder : RepoGenBaseFolder
        {
            UpdatePatientRepositoryFolders.PlexiaMainFrameFolder _plexiamainframe;
            UpdatePatientRepositoryFolders.SearchBarFolder _searchbar;

            /// <summary>
            /// Creates a new PLEXIAEMRTest3Modal  folder.
            /// </summary>
            public PLEXIAEMRTest3ModalAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PLEXIAEMRTest3Modal", "/dom[@domain='neutron.plexia.local']", parentFolder, 30000, null, false, "785ea004-1522-4869-986f-3f27b57b7427", "")
            {
                _plexiamainframe = new UpdatePatientRepositoryFolders.PlexiaMainFrameFolder(this);
                _searchbar = new UpdatePatientRepositoryFolders.SearchBarFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("785ea004-1522-4869-986f-3f27b57b7427")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("785ea004-1522-4869-986f-3f27b57b7427")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PlexiaMainFrame folder.
            /// </summary>
            [RepositoryFolder("b4700ecb-2451-4fe2-bbe3-d88c01fb2110")]
            public virtual UpdatePatientRepositoryFolders.PlexiaMainFrameFolder PlexiaMainFrame
            {
                get { return _plexiamainframe; }
            }

            /// <summary>
            /// The SearchBar folder.
            /// </summary>
            [RepositoryFolder("7a73583f-26d1-4504-addf-d40a991ff913")]
            public virtual UpdatePatientRepositoryFolders.SearchBarFolder SearchBar
            {
                get { return _searchbar; }
            }
        }

        /// <summary>
        /// The PlexiaMainFrameFolder folder.
        /// </summary>
        [RepositoryFolder("b4700ecb-2451-4fe2-bbe3-d88c01fb2110")]
        public partial class PlexiaMainFrameFolder : RepoGenBaseFolder
        {
            UpdatePatientRepositoryFolders.LoginPageFolder _loginpage;
            UpdatePatientRepositoryFolders.PersonalProfileFolder _personalprofile;
            UpdatePatientRepositoryFolders.PatientRecordsFolder _patientrecords;
            UpdatePatientRepositoryFolders.MainMenuFolder _mainmenu;
            RepoItemInfo _btnnewrichtextnoteInfo;
            RepoItemInfo _txtdobInfo;
            RepoItemInfo _imgencountersInfo;
            RepoItemInfo _linkencounterInfo;
            RepoItemInfo _imgbillingInfo;
            RepoItemInfo _btnnewbillingInfo;
            RepoItemInfo _utilitiesInfo;
            RepoItemInfo _viewInfo;
            RepoItemInfo _logoimgInfo;
            RepoItemInfo _btnlogoutInfo;

            /// <summary>
            /// Creates a new PlexiaMainFrame  folder.
            /// </summary>
            public PlexiaMainFrameFolder(RepoGenBaseFolder parentFolder) :
                    base("PlexiaMainFrame", "?/?/iframe[@id='PlexiaMainFrame']", parentFolder, 30000, null, false, "b4700ecb-2451-4fe2-bbe3-d88c01fb2110", "")
            {
                _loginpage = new UpdatePatientRepositoryFolders.LoginPageFolder(this);
                _personalprofile = new UpdatePatientRepositoryFolders.PersonalProfileFolder(this);
                _patientrecords = new UpdatePatientRepositoryFolders.PatientRecordsFolder(this);
                _mainmenu = new UpdatePatientRepositoryFolders.MainMenuFolder(this);
                _btnnewrichtextnoteInfo = new RepoItemInfo(this, "BtnNewRichTextNote", "?/?/iframe[@id='mainFrame']//form[#'Form1']/iframe[@id='ifrmmain']//input[#'btnNewRichTextNote']", 30000, null, "de97364b-0a04-4f90-936b-e454febd22f0");
                _txtdobInfo = new RepoItemInfo(this, "TxtDOB", "?/?/iframe[@id='mainFrame']//form[#'Form1']/iframe[@id='ifrmmain']//input[#'txtDOB']", 30000, null, "4f120d55-d6c0-4c64-aed8-2375183b7df1");
                _imgencountersInfo = new RepoItemInfo(this, "ImgEncounters", "?/?/iframe[@id='menuframe']//img[#'imgEncounters']", 30000, null, "66e704e7-f96c-4682-89a7-d8387481fc01");
                _linkencounterInfo = new RepoItemInfo(this, "LinkEncounter", "?/?/iframe[@id='mainFrame']//form[#'Form1']/iframe[@id='ifrmmain']//a[#'linkEncounter']", 30000, null, "01a56d72-90a6-4f5e-94a8-de74039a145e");
                _imgbillingInfo = new RepoItemInfo(this, "ImgBilling", "?/?/iframe[@id='menuframe']//img[#'imgBilling']", 30000, null, "40c514fe-c320-49a0-9ff5-a1eaa4d6661e");
                _btnnewbillingInfo = new RepoItemInfo(this, "BtnNewBilling", "?/?/iframe[@id='mainFrame']//form[#'Form1']/iframe[@id='ifrmmain']//input[#'btnNewBilling']", 30000, null, "70b2d883-451c-4b5a-9de2-ed7e4c0d1f0d");
                _utilitiesInfo = new RepoItemInfo(this, "Utilities", "?/?/iframe[@id='topFrame']//img[#'utilities']", 30000, null, "5bf49ad5-7213-4532-9f0e-b9bf1ea970a4");
                _viewInfo = new RepoItemInfo(this, "View", "?/?/iframe[@id='mainFrame']//form[#'Form1']/iframe[@id='ifrmmain']//a[#'GVEncounter_ctl03_hlView']/img[@alt='View']", 30000, null, "f58b8935-4667-40a0-80f3-bb4a7d733876");
                _logoimgInfo = new RepoItemInfo(this, "Logoimg", "?/?/iframe[@id='topFrame']//img[#'logoimg']", 30000, null, "fc9e2148-3c4d-4c7c-abac-15ab0ec40efc");
                _btnlogoutInfo = new RepoItemInfo(this, "BtnLogout", ".//input[#'btnLogout']", 30000, null, "f19478ab-993a-416b-b698-6e3bc74b485c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b4700ecb-2451-4fe2-bbe3-d88c01fb2110")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b4700ecb-2451-4fe2-bbe3-d88c01fb2110")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnNewRichTextNote item.
            /// </summary>
            [RepositoryItem("de97364b-0a04-4f90-936b-e454febd22f0")]
            public virtual Ranorex.InputTag BtnNewRichTextNote
            {
                get
                {
                    return _btnnewrichtextnoteInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnNewRichTextNote item info.
            /// </summary>
            [RepositoryItemInfo("de97364b-0a04-4f90-936b-e454febd22f0")]
            public virtual RepoItemInfo BtnNewRichTextNoteInfo
            {
                get
                {
                    return _btnnewrichtextnoteInfo;
                }
            }

            /// <summary>
            /// The TxtDOB item.
            /// </summary>
            [RepositoryItem("4f120d55-d6c0-4c64-aed8-2375183b7df1")]
            public virtual Ranorex.InputTag TxtDOB
            {
                get
                {
                    return _txtdobInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtDOB item info.
            /// </summary>
            [RepositoryItemInfo("4f120d55-d6c0-4c64-aed8-2375183b7df1")]
            public virtual RepoItemInfo TxtDOBInfo
            {
                get
                {
                    return _txtdobInfo;
                }
            }

            /// <summary>
            /// The ImgEncounters item.
            /// </summary>
            [RepositoryItem("66e704e7-f96c-4682-89a7-d8387481fc01")]
            public virtual Ranorex.ImgTag ImgEncounters
            {
                get
                {
                    return _imgencountersInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ImgEncounters item info.
            /// </summary>
            [RepositoryItemInfo("66e704e7-f96c-4682-89a7-d8387481fc01")]
            public virtual RepoItemInfo ImgEncountersInfo
            {
                get
                {
                    return _imgencountersInfo;
                }
            }

            /// <summary>
            /// The LinkEncounter item.
            /// </summary>
            [RepositoryItem("01a56d72-90a6-4f5e-94a8-de74039a145e")]
            public virtual Ranorex.ATag LinkEncounter
            {
                get
                {
                    return _linkencounterInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LinkEncounter item info.
            /// </summary>
            [RepositoryItemInfo("01a56d72-90a6-4f5e-94a8-de74039a145e")]
            public virtual RepoItemInfo LinkEncounterInfo
            {
                get
                {
                    return _linkencounterInfo;
                }
            }

            /// <summary>
            /// The ImgBilling item.
            /// </summary>
            [RepositoryItem("40c514fe-c320-49a0-9ff5-a1eaa4d6661e")]
            public virtual Ranorex.ImgTag ImgBilling
            {
                get
                {
                    return _imgbillingInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ImgBilling item info.
            /// </summary>
            [RepositoryItemInfo("40c514fe-c320-49a0-9ff5-a1eaa4d6661e")]
            public virtual RepoItemInfo ImgBillingInfo
            {
                get
                {
                    return _imgbillingInfo;
                }
            }

            /// <summary>
            /// The BtnNewBilling item.
            /// </summary>
            [RepositoryItem("70b2d883-451c-4b5a-9de2-ed7e4c0d1f0d")]
            public virtual Ranorex.InputTag BtnNewBilling
            {
                get
                {
                    return _btnnewbillingInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnNewBilling item info.
            /// </summary>
            [RepositoryItemInfo("70b2d883-451c-4b5a-9de2-ed7e4c0d1f0d")]
            public virtual RepoItemInfo BtnNewBillingInfo
            {
                get
                {
                    return _btnnewbillingInfo;
                }
            }

            /// <summary>
            /// The Utilities item.
            /// </summary>
            [RepositoryItem("5bf49ad5-7213-4532-9f0e-b9bf1ea970a4")]
            public virtual Ranorex.ImgTag Utilities
            {
                get
                {
                    return _utilitiesInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Utilities item info.
            /// </summary>
            [RepositoryItemInfo("5bf49ad5-7213-4532-9f0e-b9bf1ea970a4")]
            public virtual RepoItemInfo UtilitiesInfo
            {
                get
                {
                    return _utilitiesInfo;
                }
            }

            /// <summary>
            /// The View item.
            /// </summary>
            [RepositoryItem("f58b8935-4667-40a0-80f3-bb4a7d733876")]
            public virtual Ranorex.ImgTag View
            {
                get
                {
                    return _viewInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The View item info.
            /// </summary>
            [RepositoryItemInfo("f58b8935-4667-40a0-80f3-bb4a7d733876")]
            public virtual RepoItemInfo ViewInfo
            {
                get
                {
                    return _viewInfo;
                }
            }

            /// <summary>
            /// The Logoimg item.
            /// </summary>
            [RepositoryItem("fc9e2148-3c4d-4c7c-abac-15ab0ec40efc")]
            public virtual Ranorex.ImgTag Logoimg
            {
                get
                {
                    return _logoimgInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Logoimg item info.
            /// </summary>
            [RepositoryItemInfo("fc9e2148-3c4d-4c7c-abac-15ab0ec40efc")]
            public virtual RepoItemInfo LogoimgInfo
            {
                get
                {
                    return _logoimgInfo;
                }
            }

            /// <summary>
            /// The BtnLogout item.
            /// </summary>
            [RepositoryItem("f19478ab-993a-416b-b698-6e3bc74b485c")]
            public virtual Ranorex.InputTag BtnLogout
            {
                get
                {
                    return _btnlogoutInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnLogout item info.
            /// </summary>
            [RepositoryItemInfo("f19478ab-993a-416b-b698-6e3bc74b485c")]
            public virtual RepoItemInfo BtnLogoutInfo
            {
                get
                {
                    return _btnlogoutInfo;
                }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("4ab37009-5e24-4ba2-b403-249f7d096789")]
            public virtual UpdatePatientRepositoryFolders.LoginPageFolder LoginPage
            {
                get { return _loginpage; }
            }

            /// <summary>
            /// The PersonalProfile folder.
            /// </summary>
            [RepositoryFolder("a04c417e-00ad-425d-97d8-5e8ffaafe00e")]
            public virtual UpdatePatientRepositoryFolders.PersonalProfileFolder PersonalProfile
            {
                get { return _personalprofile; }
            }

            /// <summary>
            /// The PatientRecords folder.
            /// </summary>
            [RepositoryFolder("dc83be7f-7927-4e43-b338-6f3258fd26d4")]
            public virtual UpdatePatientRepositoryFolders.PatientRecordsFolder PatientRecords
            {
                get { return _patientrecords; }
            }

            /// <summary>
            /// The MainMenu folder.
            /// </summary>
            [RepositoryFolder("7ff87464-c618-4559-bd83-05147f054e0b")]
            public virtual UpdatePatientRepositoryFolders.MainMenuFolder MainMenu
            {
                get { return _mainmenu; }
            }
        }

        /// <summary>
        /// The LoginPageFolder folder.
        /// </summary>
        [RepositoryFolder("4ab37009-5e24-4ba2-b403-249f7d096789")]
        public partial class LoginPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnloginInfo;
            RepoItemInfo _txtusernameInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "", parentFolder, 30000, null, false, "4ab37009-5e24-4ba2-b403-249f7d096789", "")
            {
                _btnloginInfo = new RepoItemInfo(this, "BtnLogin", ".//input[#'btnLogin']", 30000, null, "cd037894-b922-46aa-9052-10b3429d654a");
                _txtusernameInfo = new RepoItemInfo(this, "TxtUserName", ".//input[#'txtUserName']", 30000, null, "564a9280-df99-4bf0-8e2b-a336d07f8caf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4ab37009-5e24-4ba2-b403-249f7d096789")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4ab37009-5e24-4ba2-b403-249f7d096789")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnLogin item.
            /// </summary>
            [RepositoryItem("cd037894-b922-46aa-9052-10b3429d654a")]
            public virtual Ranorex.InputTag BtnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnLogin item info.
            /// </summary>
            [RepositoryItemInfo("cd037894-b922-46aa-9052-10b3429d654a")]
            public virtual RepoItemInfo BtnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }

            /// <summary>
            /// The TxtUserName item.
            /// </summary>
            [RepositoryItem("564a9280-df99-4bf0-8e2b-a336d07f8caf")]
            public virtual Ranorex.InputTag TxtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtUserName item info.
            /// </summary>
            [RepositoryItemInfo("564a9280-df99-4bf0-8e2b-a336d07f8caf")]
            public virtual RepoItemInfo TxtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }
        }

        /// <summary>
        /// The PersonalProfileFolder folder.
        /// </summary>
        [RepositoryFolder("a04c417e-00ad-425d-97d8-5e8ffaafe00e")]
        public partial class PersonalProfileFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtaddr1Info;
            RepoItemInfo _btnupdatepatientInfo;

            /// <summary>
            /// Creates a new PersonalProfile  folder.
            /// </summary>
            public PersonalProfileFolder(RepoGenBaseFolder parentFolder) :
                    base("PersonalProfile", "", parentFolder, 30000, null, false, "a04c417e-00ad-425d-97d8-5e8ffaafe00e", "")
            {
                _txtaddr1Info = new RepoItemInfo(this, "TxtAddr1", "?/?/iframe[@id='mainFrame']//form[#'Form1']/iframe[@id='ifrmmain']//input[#'txtAddr1']", 30000, null, "c8d252cf-db6a-4364-affb-8974cfd1c1c3");
                _btnupdatepatientInfo = new RepoItemInfo(this, "BtnUpdatePatient", "?/?/iframe[@id='mainFrame']//form[#'Form1']/iframe[@id='ifrmmain']//input[#'btnUpdatePatient']", 30000, null, "2e9ca575-a47a-408e-8685-d824853ddc41");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a04c417e-00ad-425d-97d8-5e8ffaafe00e")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a04c417e-00ad-425d-97d8-5e8ffaafe00e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtAddr1 item.
            /// </summary>
            [RepositoryItem("c8d252cf-db6a-4364-affb-8974cfd1c1c3")]
            public virtual Ranorex.InputTag TxtAddr1
            {
                get
                {
                    return _txtaddr1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtAddr1 item info.
            /// </summary>
            [RepositoryItemInfo("c8d252cf-db6a-4364-affb-8974cfd1c1c3")]
            public virtual RepoItemInfo TxtAddr1Info
            {
                get
                {
                    return _txtaddr1Info;
                }
            }

            /// <summary>
            /// The BtnUpdatePatient item.
            /// </summary>
            [RepositoryItem("2e9ca575-a47a-408e-8685-d824853ddc41")]
            public virtual Ranorex.InputTag BtnUpdatePatient
            {
                get
                {
                    return _btnupdatepatientInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnUpdatePatient item info.
            /// </summary>
            [RepositoryItemInfo("2e9ca575-a47a-408e-8685-d824853ddc41")]
            public virtual RepoItemInfo BtnUpdatePatientInfo
            {
                get
                {
                    return _btnupdatepatientInfo;
                }
            }
        }

        /// <summary>
        /// The PatientRecordsFolder folder.
        /// </summary>
        [RepositoryFolder("dc83be7f-7927-4e43-b338-6f3258fd26d4")]
        public partial class PatientRecordsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _linkpersonalInfo;
            RepoItemInfo _linkmedicalInfo;
            RepoItemInfo _imgnotesInfo;

            /// <summary>
            /// Creates a new PatientRecords  folder.
            /// </summary>
            public PatientRecordsFolder(RepoGenBaseFolder parentFolder) :
                    base("PatientRecords", "", parentFolder, 30000, null, false, "dc83be7f-7927-4e43-b338-6f3258fd26d4", "")
            {
                _linkpersonalInfo = new RepoItemInfo(this, "LinkPersonal", "?/?/iframe[@id='mainFrame']//form[#'Form1']/iframe[@id='ifrmmain']//a[#'linkPersonal']", 30000, null, "18281774-cdb5-4c8d-a495-74801ed43a99");
                _linkmedicalInfo = new RepoItemInfo(this, "LinkMedical", "?/?/iframe[@id='mainFrame']//form[#'Form1']/iframe[@id='ifrmmain']//a[#'linkMedical']", 30000, null, "babeb0da-e235-4339-8aa5-da0607bd35db");
                _imgnotesInfo = new RepoItemInfo(this, "ImgNotes", "?/?/iframe[@id='menuframe']//img[#'imgNotes']", 30000, null, "2f8b9314-c3e3-475a-884c-0de00251da2d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dc83be7f-7927-4e43-b338-6f3258fd26d4")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dc83be7f-7927-4e43-b338-6f3258fd26d4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LinkPersonal item.
            /// </summary>
            [RepositoryItem("18281774-cdb5-4c8d-a495-74801ed43a99")]
            public virtual Ranorex.ATag LinkPersonal
            {
                get
                {
                    return _linkpersonalInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LinkPersonal item info.
            /// </summary>
            [RepositoryItemInfo("18281774-cdb5-4c8d-a495-74801ed43a99")]
            public virtual RepoItemInfo LinkPersonalInfo
            {
                get
                {
                    return _linkpersonalInfo;
                }
            }

            /// <summary>
            /// The LinkMedical item.
            /// </summary>
            [RepositoryItem("babeb0da-e235-4339-8aa5-da0607bd35db")]
            public virtual Ranorex.ATag LinkMedical
            {
                get
                {
                    return _linkmedicalInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LinkMedical item info.
            /// </summary>
            [RepositoryItemInfo("babeb0da-e235-4339-8aa5-da0607bd35db")]
            public virtual RepoItemInfo LinkMedicalInfo
            {
                get
                {
                    return _linkmedicalInfo;
                }
            }

            /// <summary>
            /// The ImgNotes item.
            /// </summary>
            [RepositoryItem("2f8b9314-c3e3-475a-884c-0de00251da2d")]
            public virtual Ranorex.ImgTag ImgNotes
            {
                get
                {
                    return _imgnotesInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ImgNotes item info.
            /// </summary>
            [RepositoryItemInfo("2f8b9314-c3e3-475a-884c-0de00251da2d")]
            public virtual RepoItemInfo ImgNotesInfo
            {
                get
                {
                    return _imgnotesInfo;
                }
            }
        }

        /// <summary>
        /// The MainMenuFolder folder.
        /// </summary>
        [RepositoryFolder("7ff87464-c618-4559-bd83-05147f054e0b")]
        public partial class MainMenuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ptrecordInfo;
            RepoItemInfo _imggoInfo;

            /// <summary>
            /// Creates a new MainMenu  folder.
            /// </summary>
            public MainMenuFolder(RepoGenBaseFolder parentFolder) :
                    base("MainMenu", "", parentFolder, 30000, null, false, "7ff87464-c618-4559-bd83-05147f054e0b", "")
            {
                _ptrecordInfo = new RepoItemInfo(this, "Ptrecord", ".//input[#'ptrecord']", 30000, null, "88f9726c-d988-4fa1-a525-b13fa0aad052");
                _imggoInfo = new RepoItemInfo(this, "ImgGo", "?/?/iframe[@id='sideframe']//input[#'imgGo']", 30000, null, "c7488181-5318-4ab8-a49c-5aa856e71d63");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ff87464-c618-4559-bd83-05147f054e0b")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ff87464-c618-4559-bd83-05147f054e0b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Ptrecord item.
            /// </summary>
            [RepositoryItem("88f9726c-d988-4fa1-a525-b13fa0aad052")]
            public virtual Ranorex.InputTag Ptrecord
            {
                get
                {
                    return _ptrecordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Ptrecord item info.
            /// </summary>
            [RepositoryItemInfo("88f9726c-d988-4fa1-a525-b13fa0aad052")]
            public virtual RepoItemInfo PtrecordInfo
            {
                get
                {
                    return _ptrecordInfo;
                }
            }

            /// <summary>
            /// The ImgGo item.
            /// </summary>
            [RepositoryItem("c7488181-5318-4ab8-a49c-5aa856e71d63")]
            public virtual Ranorex.InputTag ImgGo
            {
                get
                {
                    return _imggoInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ImgGo item info.
            /// </summary>
            [RepositoryItemInfo("c7488181-5318-4ab8-a49c-5aa856e71d63")]
            public virtual RepoItemInfo ImgGoInfo
            {
                get
                {
                    return _imggoInfo;
                }
            }
        }

        /// <summary>
        /// The SearchBarFolder folder.
        /// </summary>
        [RepositoryFolder("7a73583f-26d1-4504-addf-d40a991ff913")]
        public partial class SearchBarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _aaronsiskindInfo;
            RepoItemInfo _btncancelInfo;
            RepoItemInfo _htmlInfo;
            RepoItemInfo _richtextboxhtmlInfo;
            RepoItemInfo _designInfo;
            RepoItemInfo _testingInfo;
            RepoItemInfo _justifycenterInfo;
            RepoItemInfo _justifyrightInfo;
            RepoItemInfo _justifyleftInfo;
            RepoItemInfo _line1Info;
            RepoItemInfo _line2Info;
            RepoItemInfo _line3Info;
            RepoItemInfo _line4Info;
            RepoItemInfo _line5Info;
            RepoItemInfo _txtbilledfeeitemInfo;
            RepoItemInfo _sometdtagInfo;
            RepoItemInfo _txtservicedateInfo;
            RepoItemInfo _billing1txtfee1Info;
            RepoItemInfo _billing1txtfee2Info;
            RepoItemInfo _billing1txtfee3Info;
            RepoItemInfo _btncancel1Info;
            RepoItemInfo _btncancel2Info;
            RepoItemInfo _patientheaderpopup1ctl02Info;
            RepoItemInfo _ddlpageInfo;
            RepoItemInfo _btnusecurrptInfo;
            RepoItemInfo _quickcreatefeeInfo;
            RepoItemInfo _btnrefreshInfo;
            RepoItemInfo _servicedateInfo;

            /// <summary>
            /// Creates a new SearchBar  folder.
            /// </summary>
            public SearchBarFolder(RepoGenBaseFolder parentFolder) :
                    base("SearchBar", "", parentFolder, 30000, null, false, "7a73583f-26d1-4504-addf-d40a991ff913", "")
            {
                _aaronsiskindInfo = new RepoItemInfo(this, "AaronSiskind", ".//form[#'physicianSearchMain']/iframe[@id='ifrmmain']//table[#'dataGridSearch']//span[@innertext='Aaron, Siskind']", 30000, null, "f959ad1c-adc3-4008-b01a-46be10c9f40e");
                _btncancelInfo = new RepoItemInfo(this, "BtnCancel", ".//form[#'physicianSearchMain']/?/?//input[#'btnCancel']", 30000, null, "0a4220ff-2c3b-42cb-b2c9-c8ee1ccdbf3b");
                _htmlInfo = new RepoItemInfo(this, "HTML", ".//form[#'Form1']/iframe[@id='ifrmmain']//div[#'ctl00_ContentPlaceHolder1_radEditor_ModesWrapper']/ul//span[@innertext='HTML']", 30000, null, "aaf6ab13-0501-4ba5-a1ca-a7a662de6176");
                _richtextboxhtmlInfo = new RepoItemInfo(this, "RichtextboxHTML", ".//form[#'Form1']/iframe[@id='ifrmmain']//td[#'ctl00_ContentPlaceHolder1_radEditorCenter']/?/?/body/textarea[@wrap='soft' or @required='False']", 30000, null, "d393cfee-f653-481b-be7d-3f14f7138b4f");
                _designInfo = new RepoItemInfo(this, "Design", ".//form[#'Form1']/iframe[@id='ifrmmain']//div[#'ctl00_ContentPlaceHolder1_radEditor_ModesWrapper']/ul//span[@innertext='Design']", 30000, null, "d13f5dca-e7ee-4369-97e1-88b4b80bdec9");
                _testingInfo = new RepoItemInfo(this, "Testing", ".//form[#'Form1']/?/?/?//tag[@innertext='Testing']", 30000, null, "97a03d92-fd89-4b46-8d18-2da8cc5597f1");
                _justifycenterInfo = new RepoItemInfo(this, "JustifyCenter", ".//form[#'Form1']/iframe[@id='ifrmmain']//td[#'ctl00_ContentPlaceHolder1_radEditorTop']/div/ul[5]/?/?/a[@title='Align Center']/span", 30000, null, "6627df20-d60e-4aaa-9d0c-bf0078aefe1f");
                _justifyrightInfo = new RepoItemInfo(this, "JustifyRight", ".//form[#'Form1']/iframe[@id='ifrmmain']//td[#'ctl00_ContentPlaceHolder1_radEditorTop']/div/ul[5]/?/?/a[@title='Align Right']/span", 30000, null, "393992ec-443b-4462-add3-b24d5fdff126");
                _justifyleftInfo = new RepoItemInfo(this, "JustifyLeft", ".//form[#'Form1']/iframe[@id='ifrmmain']//td[#'ctl00_ContentPlaceHolder1_radEditorTop']/div/ul[5]//span", 30000, null, "faf039f7-1457-471a-8a73-06ff3252bd7e");
                _line1Info = new RepoItemInfo(this, "Line1", ".//form[#'Form1']/?/?//div[#'ctl00_ContentPlaceHolder1_radEditor_contentDiv']/p[@innertext='line1']", 30000, null, "8b018663-6736-46c7-aa32-b6b236e94791");
                _line2Info = new RepoItemInfo(this, "Line2", ".//form[#'Form1']/?/?//div[#'ctl00_ContentPlaceHolder1_radEditor_contentDiv']/p[@innertext='line2']", 30000, null, "0fea5866-e602-430d-95b6-c01f5550f10c");
                _line3Info = new RepoItemInfo(this, "Line3", ".//form[#'Form1']/?/?//div[#'ctl00_ContentPlaceHolder1_radEditor_contentDiv']/p[@innertext='line3']", 30000, null, "4412374f-5f1a-4f7e-b352-8798a1cf4621");
                _line4Info = new RepoItemInfo(this, "Line4", ".//form[#'Form1']/?/?//div[#'ctl00_ContentPlaceHolder1_radEditor_contentDiv']/p[@innertext='line4']", 30000, null, "b6c2cff3-5f0f-453b-ab04-21bf00b338d5");
                _line5Info = new RepoItemInfo(this, "Line5", ".//form[#'Form1']/?/?//div[#'ctl00_ContentPlaceHolder1_radEditor_contentDiv']/p[@innertext='line5']", 30000, null, "bfa91574-80a6-4b41-ab7b-acfdeb9ab6ea");
                _txtbilledfeeitemInfo = new RepoItemInfo(this, "TxtBilledFeeItem", ".//form[#'Form1']/table//iframe[@id='ifrmmain']//input[#'txtBilledFeeItem']", 30000, null, "a9d5a768-2d8e-4f36-88c2-d3b34957ef71");
                _sometdtagInfo = new RepoItemInfo(this, "SomeTdTag", ".//form[#'Form1']/table//iframe[@id='ifrmmain']//table[#'tblTop']/tbody/tr[2]/td[2]", 30000, null, "a5395c59-d1b7-464c-b6ea-4837a42be6b2");
                _txtservicedateInfo = new RepoItemInfo(this, "TxtServiceDate", ".//form[#'Form1']/table//iframe[@id='ifrmmain']//input[#'txtServiceDate']", 30000, null, "afe3a9a1-fb22-4fe9-86a0-a29b59fe02ba");
                _billing1txtfee1Info = new RepoItemInfo(this, "Billing1TxtFee1", ".//form[#'form1']/?/?//input[#'Billing1_txtFee1']", 30000, null, "197c9b1b-b992-419d-86b6-8092a2a5c942");
                _billing1txtfee2Info = new RepoItemInfo(this, "Billing1TxtFee2", ".//form[#'form1']/?/?//input[#'Billing1_txtFee2']", 30000, null, "cd6d7d2e-8386-48a8-b2e5-15d8580cd3b2");
                _billing1txtfee3Info = new RepoItemInfo(this, "Billing1TxtFee3", ".//form[#'form1']/?/?//input[#'Billing1_txtFee3']", 30000, null, "f90e2d26-2c96-4b37-9bb8-1c4bca7d8537");
                _btncancel1Info = new RepoItemInfo(this, "BtnCancel1", ".//form[#'form1']/?/?//input[#'btnCancel']", 30000, null, "be044e5e-c992-489c-b3c2-f4af4588d55d");
                _btncancel2Info = new RepoItemInfo(this, "BtnCancel2", ".//form[#'Form1']/table//iframe[@id='ifrmmain']//input[#'btnCancel']", 30000, null, "1f0e9adb-510d-4893-b57e-314723eea79b");
                _patientheaderpopup1ctl02Info = new RepoItemInfo(this, "PatientHeaderPopup1Ctl02", ".//form[#'form1']/?/?//td[#'PatientHeaderPopup1_ctl02']", 30000, null, "8a9f5941-820b-4e03-bcd4-cb592cd2b372");
                _ddlpageInfo = new RepoItemInfo(this, "DdlPage", "?/?/frame[@name='top']//select[#'ddlPage']", 30000, null, "353e375a-e636-4286-838a-8bbd1e043235");
                _btnusecurrptInfo = new RepoItemInfo(this, "btnUseCurrPt", "?/?/frame[@id='recallmain']//input[#'ctl00_ContentPlaceHolder1_PatientSearch1_btnUseCurrPt']", 30000, null, "2756fb61-0717-4462-8e36-f75b73acbac5");
                _quickcreatefeeInfo = new RepoItemInfo(this, "QuickCreateFee", "?/?/frame[@id='recallmain']//input[#'ctl00_ContentPlaceHolder1_lblFEE']", 30000, null, "4599d11a-cf4e-40a3-ba5b-4249bc1d7283");
                _btnrefreshInfo = new RepoItemInfo(this, "btnRefresh", "?/?/frame[@id='recallmain']//input[#'ctl00_ContentPlaceHolder1_btnRefreshSimpleBill']", 30000, null, "73b58c5c-e829-4f02-ba0f-f359fc7144af");
                _servicedateInfo = new RepoItemInfo(this, "ServiceDate", "?/?/frame[@id='recallmain']//input[#'ctl00_ContentPlaceHolder1_txtServiceDate']", 30000, null, "0848adfa-1719-4cd6-ae00-47b5debb1e17");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7a73583f-26d1-4504-addf-d40a991ff913")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7a73583f-26d1-4504-addf-d40a991ff913")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AaronSiskind item.
            /// </summary>
            [RepositoryItem("f959ad1c-adc3-4008-b01a-46be10c9f40e")]
            public virtual Ranorex.SpanTag AaronSiskind
            {
                get
                {
                    return _aaronsiskindInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AaronSiskind item info.
            /// </summary>
            [RepositoryItemInfo("f959ad1c-adc3-4008-b01a-46be10c9f40e")]
            public virtual RepoItemInfo AaronSiskindInfo
            {
                get
                {
                    return _aaronsiskindInfo;
                }
            }

            /// <summary>
            /// The BtnCancel item.
            /// </summary>
            [RepositoryItem("0a4220ff-2c3b-42cb-b2c9-c8ee1ccdbf3b")]
            public virtual Ranorex.InputTag BtnCancel
            {
                get
                {
                    return _btncancelInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnCancel item info.
            /// </summary>
            [RepositoryItemInfo("0a4220ff-2c3b-42cb-b2c9-c8ee1ccdbf3b")]
            public virtual RepoItemInfo BtnCancelInfo
            {
                get
                {
                    return _btncancelInfo;
                }
            }

            /// <summary>
            /// The HTML item.
            /// </summary>
            [RepositoryItem("aaf6ab13-0501-4ba5-a1ca-a7a662de6176")]
            public virtual Ranorex.SpanTag HTML
            {
                get
                {
                    return _htmlInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The HTML item info.
            /// </summary>
            [RepositoryItemInfo("aaf6ab13-0501-4ba5-a1ca-a7a662de6176")]
            public virtual RepoItemInfo HTMLInfo
            {
                get
                {
                    return _htmlInfo;
                }
            }

            /// <summary>
            /// The RichtextboxHTML item.
            /// </summary>
            [RepositoryItem("d393cfee-f653-481b-be7d-3f14f7138b4f")]
            public virtual Ranorex.TextAreaTag RichtextboxHTML
            {
                get
                {
                    return _richtextboxhtmlInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The RichtextboxHTML item info.
            /// </summary>
            [RepositoryItemInfo("d393cfee-f653-481b-be7d-3f14f7138b4f")]
            public virtual RepoItemInfo RichtextboxHTMLInfo
            {
                get
                {
                    return _richtextboxhtmlInfo;
                }
            }

            /// <summary>
            /// The Design item.
            /// </summary>
            [RepositoryItem("d13f5dca-e7ee-4369-97e1-88b4b80bdec9")]
            public virtual Ranorex.SpanTag Design
            {
                get
                {
                    return _designInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Design item info.
            /// </summary>
            [RepositoryItemInfo("d13f5dca-e7ee-4369-97e1-88b4b80bdec9")]
            public virtual RepoItemInfo DesignInfo
            {
                get
                {
                    return _designInfo;
                }
            }

            /// <summary>
            /// The Testing item.
            /// </summary>
            [RepositoryItem("97a03d92-fd89-4b46-8d18-2da8cc5597f1")]
            public virtual Ranorex.WebElement Testing
            {
                get
                {
                    return _testingInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Testing item info.
            /// </summary>
            [RepositoryItemInfo("97a03d92-fd89-4b46-8d18-2da8cc5597f1")]
            public virtual RepoItemInfo TestingInfo
            {
                get
                {
                    return _testingInfo;
                }
            }

            /// <summary>
            /// The JustifyCenter item.
            /// </summary>
            [RepositoryItem("6627df20-d60e-4aaa-9d0c-bf0078aefe1f")]
            public virtual Ranorex.SpanTag JustifyCenter
            {
                get
                {
                    return _justifycenterInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The JustifyCenter item info.
            /// </summary>
            [RepositoryItemInfo("6627df20-d60e-4aaa-9d0c-bf0078aefe1f")]
            public virtual RepoItemInfo JustifyCenterInfo
            {
                get
                {
                    return _justifycenterInfo;
                }
            }

            /// <summary>
            /// The JustifyRight item.
            /// </summary>
            [RepositoryItem("393992ec-443b-4462-add3-b24d5fdff126")]
            public virtual Ranorex.SpanTag JustifyRight
            {
                get
                {
                    return _justifyrightInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The JustifyRight item info.
            /// </summary>
            [RepositoryItemInfo("393992ec-443b-4462-add3-b24d5fdff126")]
            public virtual RepoItemInfo JustifyRightInfo
            {
                get
                {
                    return _justifyrightInfo;
                }
            }

            /// <summary>
            /// The JustifyLeft item.
            /// </summary>
            [RepositoryItem("faf039f7-1457-471a-8a73-06ff3252bd7e")]
            public virtual Ranorex.SpanTag JustifyLeft
            {
                get
                {
                    return _justifyleftInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The JustifyLeft item info.
            /// </summary>
            [RepositoryItemInfo("faf039f7-1457-471a-8a73-06ff3252bd7e")]
            public virtual RepoItemInfo JustifyLeftInfo
            {
                get
                {
                    return _justifyleftInfo;
                }
            }

            /// <summary>
            /// The Line1 item.
            /// </summary>
            [RepositoryItem("8b018663-6736-46c7-aa32-b6b236e94791")]
            public virtual Ranorex.PTag Line1
            {
                get
                {
                    return _line1Info.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Line1 item info.
            /// </summary>
            [RepositoryItemInfo("8b018663-6736-46c7-aa32-b6b236e94791")]
            public virtual RepoItemInfo Line1Info
            {
                get
                {
                    return _line1Info;
                }
            }

            /// <summary>
            /// The Line2 item.
            /// </summary>
            [RepositoryItem("0fea5866-e602-430d-95b6-c01f5550f10c")]
            public virtual Ranorex.PTag Line2
            {
                get
                {
                    return _line2Info.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Line2 item info.
            /// </summary>
            [RepositoryItemInfo("0fea5866-e602-430d-95b6-c01f5550f10c")]
            public virtual RepoItemInfo Line2Info
            {
                get
                {
                    return _line2Info;
                }
            }

            /// <summary>
            /// The Line3 item.
            /// </summary>
            [RepositoryItem("4412374f-5f1a-4f7e-b352-8798a1cf4621")]
            public virtual Ranorex.PTag Line3
            {
                get
                {
                    return _line3Info.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Line3 item info.
            /// </summary>
            [RepositoryItemInfo("4412374f-5f1a-4f7e-b352-8798a1cf4621")]
            public virtual RepoItemInfo Line3Info
            {
                get
                {
                    return _line3Info;
                }
            }

            /// <summary>
            /// The Line4 item.
            /// </summary>
            [RepositoryItem("b6c2cff3-5f0f-453b-ab04-21bf00b338d5")]
            public virtual Ranorex.PTag Line4
            {
                get
                {
                    return _line4Info.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Line4 item info.
            /// </summary>
            [RepositoryItemInfo("b6c2cff3-5f0f-453b-ab04-21bf00b338d5")]
            public virtual RepoItemInfo Line4Info
            {
                get
                {
                    return _line4Info;
                }
            }

            /// <summary>
            /// The Line5 item.
            /// </summary>
            [RepositoryItem("bfa91574-80a6-4b41-ab7b-acfdeb9ab6ea")]
            public virtual Ranorex.PTag Line5
            {
                get
                {
                    return _line5Info.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Line5 item info.
            /// </summary>
            [RepositoryItemInfo("bfa91574-80a6-4b41-ab7b-acfdeb9ab6ea")]
            public virtual RepoItemInfo Line5Info
            {
                get
                {
                    return _line5Info;
                }
            }

            /// <summary>
            /// The TxtBilledFeeItem item.
            /// </summary>
            [RepositoryItem("a9d5a768-2d8e-4f36-88c2-d3b34957ef71")]
            public virtual Ranorex.InputTag TxtBilledFeeItem
            {
                get
                {
                    return _txtbilledfeeitemInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtBilledFeeItem item info.
            /// </summary>
            [RepositoryItemInfo("a9d5a768-2d8e-4f36-88c2-d3b34957ef71")]
            public virtual RepoItemInfo TxtBilledFeeItemInfo
            {
                get
                {
                    return _txtbilledfeeitemInfo;
                }
            }

            /// <summary>
            /// The SomeTdTag item.
            /// </summary>
            [RepositoryItem("a5395c59-d1b7-464c-b6ea-4837a42be6b2")]
            public virtual Ranorex.TdTag SomeTdTag
            {
                get
                {
                    return _sometdtagInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The SomeTdTag item info.
            /// </summary>
            [RepositoryItemInfo("a5395c59-d1b7-464c-b6ea-4837a42be6b2")]
            public virtual RepoItemInfo SomeTdTagInfo
            {
                get
                {
                    return _sometdtagInfo;
                }
            }

            /// <summary>
            /// The TxtServiceDate item.
            /// </summary>
            [RepositoryItem("afe3a9a1-fb22-4fe9-86a0-a29b59fe02ba")]
            public virtual Ranorex.InputTag TxtServiceDate
            {
                get
                {
                    return _txtservicedateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtServiceDate item info.
            /// </summary>
            [RepositoryItemInfo("afe3a9a1-fb22-4fe9-86a0-a29b59fe02ba")]
            public virtual RepoItemInfo TxtServiceDateInfo
            {
                get
                {
                    return _txtservicedateInfo;
                }
            }

            /// <summary>
            /// The Billing1TxtFee1 item.
            /// </summary>
            [RepositoryItem("197c9b1b-b992-419d-86b6-8092a2a5c942")]
            public virtual Ranorex.InputTag Billing1TxtFee1
            {
                get
                {
                    return _billing1txtfee1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Billing1TxtFee1 item info.
            /// </summary>
            [RepositoryItemInfo("197c9b1b-b992-419d-86b6-8092a2a5c942")]
            public virtual RepoItemInfo Billing1TxtFee1Info
            {
                get
                {
                    return _billing1txtfee1Info;
                }
            }

            /// <summary>
            /// The Billing1TxtFee2 item.
            /// </summary>
            [RepositoryItem("cd6d7d2e-8386-48a8-b2e5-15d8580cd3b2")]
            public virtual Ranorex.InputTag Billing1TxtFee2
            {
                get
                {
                    return _billing1txtfee2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Billing1TxtFee2 item info.
            /// </summary>
            [RepositoryItemInfo("cd6d7d2e-8386-48a8-b2e5-15d8580cd3b2")]
            public virtual RepoItemInfo Billing1TxtFee2Info
            {
                get
                {
                    return _billing1txtfee2Info;
                }
            }

            /// <summary>
            /// The Billing1TxtFee3 item.
            /// </summary>
            [RepositoryItem("f90e2d26-2c96-4b37-9bb8-1c4bca7d8537")]
            public virtual Ranorex.InputTag Billing1TxtFee3
            {
                get
                {
                    return _billing1txtfee3Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Billing1TxtFee3 item info.
            /// </summary>
            [RepositoryItemInfo("f90e2d26-2c96-4b37-9bb8-1c4bca7d8537")]
            public virtual RepoItemInfo Billing1TxtFee3Info
            {
                get
                {
                    return _billing1txtfee3Info;
                }
            }

            /// <summary>
            /// The BtnCancel1 item.
            /// </summary>
            [RepositoryItem("be044e5e-c992-489c-b3c2-f4af4588d55d")]
            public virtual Ranorex.InputTag BtnCancel1
            {
                get
                {
                    return _btncancel1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnCancel1 item info.
            /// </summary>
            [RepositoryItemInfo("be044e5e-c992-489c-b3c2-f4af4588d55d")]
            public virtual RepoItemInfo BtnCancel1Info
            {
                get
                {
                    return _btncancel1Info;
                }
            }

            /// <summary>
            /// The BtnCancel2 item.
            /// </summary>
            [RepositoryItem("1f0e9adb-510d-4893-b57e-314723eea79b")]
            public virtual Ranorex.InputTag BtnCancel2
            {
                get
                {
                    return _btncancel2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnCancel2 item info.
            /// </summary>
            [RepositoryItemInfo("1f0e9adb-510d-4893-b57e-314723eea79b")]
            public virtual RepoItemInfo BtnCancel2Info
            {
                get
                {
                    return _btncancel2Info;
                }
            }

            /// <summary>
            /// The PatientHeaderPopup1Ctl02 item.
            /// </summary>
            [RepositoryItem("8a9f5941-820b-4e03-bcd4-cb592cd2b372")]
            public virtual Ranorex.TdTag PatientHeaderPopup1Ctl02
            {
                get
                {
                    return _patientheaderpopup1ctl02Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The PatientHeaderPopup1Ctl02 item info.
            /// </summary>
            [RepositoryItemInfo("8a9f5941-820b-4e03-bcd4-cb592cd2b372")]
            public virtual RepoItemInfo PatientHeaderPopup1Ctl02Info
            {
                get
                {
                    return _patientheaderpopup1ctl02Info;
                }
            }

            /// <summary>
            /// The DdlPage item.
            /// </summary>
            [RepositoryItem("353e375a-e636-4286-838a-8bbd1e043235")]
            public virtual Ranorex.SelectTag DdlPage
            {
                get
                {
                    return _ddlpageInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DdlPage item info.
            /// </summary>
            [RepositoryItemInfo("353e375a-e636-4286-838a-8bbd1e043235")]
            public virtual RepoItemInfo DdlPageInfo
            {
                get
                {
                    return _ddlpageInfo;
                }
            }

            /// <summary>
            /// The btnUseCurrPt item.
            /// </summary>
            [RepositoryItem("2756fb61-0717-4462-8e36-f75b73acbac5")]
            public virtual Ranorex.InputTag btnUseCurrPt
            {
                get
                {
                    return _btnusecurrptInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The btnUseCurrPt item info.
            /// </summary>
            [RepositoryItemInfo("2756fb61-0717-4462-8e36-f75b73acbac5")]
            public virtual RepoItemInfo btnUseCurrPtInfo
            {
                get
                {
                    return _btnusecurrptInfo;
                }
            }

            /// <summary>
            /// The QuickCreateFee item.
            /// </summary>
            [RepositoryItem("4599d11a-cf4e-40a3-ba5b-4249bc1d7283")]
            public virtual Ranorex.InputTag QuickCreateFee
            {
                get
                {
                    return _quickcreatefeeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The QuickCreateFee item info.
            /// </summary>
            [RepositoryItemInfo("4599d11a-cf4e-40a3-ba5b-4249bc1d7283")]
            public virtual RepoItemInfo QuickCreateFeeInfo
            {
                get
                {
                    return _quickcreatefeeInfo;
                }
            }

            /// <summary>
            /// The btnRefresh item.
            /// </summary>
            [RepositoryItem("73b58c5c-e829-4f02-ba0f-f359fc7144af")]
            public virtual Ranorex.InputTag btnRefresh
            {
                get
                {
                    return _btnrefreshInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The btnRefresh item info.
            /// </summary>
            [RepositoryItemInfo("73b58c5c-e829-4f02-ba0f-f359fc7144af")]
            public virtual RepoItemInfo btnRefreshInfo
            {
                get
                {
                    return _btnrefreshInfo;
                }
            }

            /// <summary>
            /// The ServiceDate item.
            /// </summary>
            [RepositoryItem("0848adfa-1719-4cd6-ae00-47b5debb1e17")]
            public virtual Ranorex.InputTag ServiceDate
            {
                get
                {
                    return _servicedateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ServiceDate item info.
            /// </summary>
            [RepositoryItemInfo("0848adfa-1719-4cd6-ae00-47b5debb1e17")]
            public virtual RepoItemInfo ServiceDateInfo
            {
                get
                {
                    return _servicedateInfo;
                }
            }
        }

        /// <summary>
        /// The OutstandingPopUpModalAppFolder folder.
        /// </summary>
        [RepositoryFolder("0264dd79-1ad5-4ee9-b70a-c2741ed90c3d")]
        public partial class OutstandingPopUpModalAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new OutstandingPopUpModal  folder.
            /// </summary>
            public OutstandingPopUpModalAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OutstandingPopUpModal", "/form[@title~'^Utilities\\ -\\ Plexia\\ EMR\\ -\\ ']", parentFolder, 30000, null, true, "0264dd79-1ad5-4ee9-b70a-c2741ed90c3d", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "b255f951-093b-41d3-8ebe-463a5b1d3034");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0264dd79-1ad5-4ee9-b70a-c2741ed90c3d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0264dd79-1ad5-4ee9-b70a-c2741ed90c3d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("b255f951-093b-41d3-8ebe-463a5b1d3034")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("b255f951-093b-41d3-8ebe-463a5b1d3034")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The HttpsNeutronPlexiaLocalUtilitieAppFolder folder.
        /// </summary>
        [RepositoryFolder("16ca41fb-0a34-4088-b717-b5fd2811a53a")]
        public partial class HttpsNeutronPlexiaLocalUtilitieAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new HttpsNeutronPlexiaLocalUtilitie  folder.
            /// </summary>
            public HttpsNeutronPlexiaLocalUtilitieAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsNeutronPlexiaLocalUtilitie", "/form[@title~'^https://neutron\\.plexia\\.lo']", parentFolder, 30000, null, true, "16ca41fb-0a34-4088-b717-b5fd2811a53a", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "9b83333d-9a09-4407-8c0c-71a725c2a403");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("16ca41fb-0a34-4088-b717-b5fd2811a53a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("16ca41fb-0a34-4088-b717-b5fd2811a53a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("9b83333d-9a09-4407-8c0c-71a725c2a403")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("9b83333d-9a09-4407-8c0c-71a725c2a403")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
}