///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UpdatePatient
{
    /// <summary>
    ///The Utilties recording.
    /// </summary>
    [TestModule("ca737f3f-2f1f-407a-90c8-e081aeff2bae", ModuleType.Recording, 1)]
    public partial class Utilties : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UpdatePatientRepository repository.
        /// </summary>
        public static UpdatePatientRepository repo = UpdatePatientRepository.Instance;

        static Utilties instance = new Utilties();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Utilties()
        {
            QuickFee = "16100";
            QuickFee2 = "16100";
            QuickFee3 = "16100";
            ServiceDate = "";
            ServiceFee = "16100";
            ServiceFee2 = "16100";
            ServiceFee3 = "16100";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Utilties Instance
        {
            get { return instance; }
        }

#region Variables

        string _QuickFee;

        /// <summary>
        /// Gets or sets the value of variable QuickFee.
        /// </summary>
        [TestVariable("b5667ec8-3028-4a2b-a2da-09db91e82a46")]
        public string QuickFee
        {
            get { return _QuickFee; }
            set { _QuickFee = value; }
        }

        string _QuickFee2;

        /// <summary>
        /// Gets or sets the value of variable QuickFee2.
        /// </summary>
        [TestVariable("7087cd98-b8bf-4a3e-a34f-d6a97d8b4168")]
        public string QuickFee2
        {
            get { return _QuickFee2; }
            set { _QuickFee2 = value; }
        }

        string _QuickFee3;

        /// <summary>
        /// Gets or sets the value of variable QuickFee3.
        /// </summary>
        [TestVariable("96e07fb5-ea3e-4d2e-a48f-f68013235035")]
        public string QuickFee3
        {
            get { return _QuickFee3; }
            set { _QuickFee3 = value; }
        }

        string _ServiceDate;

        /// <summary>
        /// Gets or sets the value of variable ServiceDate.
        /// </summary>
        [TestVariable("b3b771d2-2942-499c-bbaf-4bce9c3e6f48")]
        public string ServiceDate
        {
            get { return _ServiceDate; }
            set { _ServiceDate = value; }
        }

        string _ServiceFee;

        /// <summary>
        /// Gets or sets the value of variable ServiceFee.
        /// </summary>
        [TestVariable("32d064f3-0a8f-4c25-910f-63bd4af6e326")]
        public string ServiceFee
        {
            get { return _ServiceFee; }
            set { _ServiceFee = value; }
        }

        string _ServiceFee2;

        /// <summary>
        /// Gets or sets the value of variable ServiceFee2.
        /// </summary>
        [TestVariable("7e20a9c0-f1c5-4512-9390-52fc80efc43a")]
        public string ServiceFee2
        {
            get { return _ServiceFee2; }
            set { _ServiceFee2 = value; }
        }

        string _ServiceFee3;

        /// <summary>
        /// Gets or sets the value of variable ServiceFee3.
        /// </summary>
        [TestVariable("721e5753-fb41-454f-b96c-339b7cd9a768")]
        public string ServiceFee3
        {
            get { return _ServiceFee3; }
            set { _ServiceFee3 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.PlexiaMainFrame.Utilities' at 41;34.", repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.UtilitiesInfo, new RecordItemIndex(0));
            repo.PLEXIAEMRTest3Modal.PlexiaMainFrame.Utilities.Click("41;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.DdlPage' at 175;12.", repo.PLEXIAEMRTest3Modal.SearchBar.DdlPageInfo, new RecordItemIndex(1));
            repo.PLEXIAEMRTest3Modal.SearchBar.DdlPage.Click("175;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'msp billing '.", new RecordItemIndex(2));
            Keyboard.Press("msp billing ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(3));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.btnUseCurrPt' at 20;12.", repo.PLEXIAEMRTest3Modal.SearchBar.btnUseCurrPtInfo, new RecordItemIndex(4));
            repo.PLEXIAEMRTest3Modal.SearchBar.btnUseCurrPt.Click("20;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee' at 15;1.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(5));
            repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee.Click("15;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}100' with focus on 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(6));
            repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee.PressKeys("{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.btnRefresh' at 31;14.", repo.PLEXIAEMRTest3Modal.SearchBar.btnRefreshInfo, new RecordItemIndex(7));
            repo.PLEXIAEMRTest3Modal.SearchBar.btnRefresh.Click("31;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value=$QuickFee) on item 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, "Value", QuickFee);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}101' with focus on 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(9));
            repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee.PressKeys("{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}101");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.btnRefresh' at 31;14.", repo.PLEXIAEMRTest3Modal.SearchBar.btnRefreshInfo, new RecordItemIndex(10));
            repo.PLEXIAEMRTest3Modal.SearchBar.btnRefresh.Click("31;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value=$QuickFee2) on item 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, "Value", QuickFee2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}110' with focus on 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(12));
            repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee.PressKeys("{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}110");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.btnRefresh' at 31;14.", repo.PLEXIAEMRTest3Modal.SearchBar.btnRefreshInfo, new RecordItemIndex(13));
            repo.PLEXIAEMRTest3Modal.SearchBar.btnRefresh.Click("31;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value=$QuickFee3) on item 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(14));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, "Value", QuickFee3);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.ServiceDate' at 43;12.", repo.PLEXIAEMRTest3Modal.SearchBar.ServiceDateInfo, new RecordItemIndex(15));
            repo.PLEXIAEMRTest3Modal.SearchBar.ServiceDate.Click("43;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}' with focus on 'PLEXIAEMRTest3Modal.SearchBar.ServiceDate'.", repo.PLEXIAEMRTest3Modal.SearchBar.ServiceDateInfo, new RecordItemIndex(16));
            repo.PLEXIAEMRTest3Modal.SearchBar.ServiceDate.PressKeys("{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $ServiceDate with focus on 'PLEXIAEMRTest3Modal.SearchBar.ServiceDate'.", repo.PLEXIAEMRTest3Modal.SearchBar.ServiceDateInfo, new RecordItemIndex(17));
            repo.PLEXIAEMRTest3Modal.SearchBar.ServiceDate.PressKeys(ServiceDate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.btnRefresh' at 31;14.", repo.PLEXIAEMRTest3Modal.SearchBar.btnRefreshInfo, new RecordItemIndex(18));
            repo.PLEXIAEMRTest3Modal.SearchBar.btnRefresh.Click("31;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee' at 15;1.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(19));
            repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee.Click("15;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}100' with focus on 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(20));
            repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee.PressKeys("{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.btnRefresh' at 31;14.", repo.PLEXIAEMRTest3Modal.SearchBar.btnRefreshInfo, new RecordItemIndex(21));
            repo.PLEXIAEMRTest3Modal.SearchBar.btnRefresh.Click("31;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value=$ServiceFee) on item 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(22));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, "Value", ServiceFee);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}101' with focus on 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(23));
            repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee.PressKeys("{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}101");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.btnRefresh' at 31;14.", repo.PLEXIAEMRTest3Modal.SearchBar.btnRefreshInfo, new RecordItemIndex(24));
            repo.PLEXIAEMRTest3Modal.SearchBar.btnRefresh.Click("31;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value=$ServiceFee2) on item 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(25));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, "Value", ServiceFee2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}110' with focus on 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(26));
            repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee.PressKeys("{END}{SHIFT DOWN}{HOME}{SHIFT UP}{DELETE}110");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PLEXIAEMRTest3Modal.SearchBar.btnRefresh' at 31;14.", repo.PLEXIAEMRTest3Modal.SearchBar.btnRefreshInfo, new RecordItemIndex(27));
            repo.PLEXIAEMRTest3Modal.SearchBar.btnRefresh.Click("31;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value=$ServiceFee3) on item 'PLEXIAEMRTest3Modal.SearchBar.QuickCreateFee'.", repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, new RecordItemIndex(28));
            Validate.Attribute(repo.PLEXIAEMRTest3Modal.SearchBar.QuickCreateFeeInfo, "Value", ServiceFee3);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsNeutronPlexiaLocalUtilitie.Close' at 18;10.", repo.HttpsNeutronPlexiaLocalUtilitie.CloseInfo, new RecordItemIndex(29));
            repo.HttpsNeutronPlexiaLocalUtilitie.Close.Click("18;10");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
}
